apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: product-catalog-api 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: catalog-api 
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: product-catalog-api
        image: mongo:5.0
        ports:
        - containerPort: 3000

