apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
  namespace: product-catalog
data:
  NODE_ENV: "development"
  PORT: "3000"
  MONGO_URI: "mongodb://product-catalog-mongodb:27017/product-catalog" 